### ISSUE TITLE
color representation for deeper variables

### ISSUE THREAD

**Issue by terragady** [vunguyentuan/vscode-css-variables#100]
Hi is it possible to have a color representation if I use nested variables? for example

```css

:root {
--color: rgb(0,0,0);
--color-alias: var(--color);
}
```

and then when I am using `--color` i do have a color show but if i use `--color-alias` i do not get it. Is it possible to have it?
