### ISSUE TITLE
double-slash comment in scss style rule causes problems

### ISSUE THREAD

**Issue by paulrudy** [vunguyentuan/vscode-css-variables#39]
Hi, thanks for your extension!

With v2.4.2, I found the following issue. In an `.scss` file with:
```scss
:root {
  // comment here
  --some-variable: #ffffff;
  --another-variable: #000000;
}
```
The presence of the comment causes the extension to stop suggesting those variables.  v2.3.12 doesn't seem to have this problem.
