### ISSUE TITLE
Duplicate values in list

### ISSUE THREAD

**Issue by literalpie** [vunguyentuan/vscode-css-variables#9]
Thanks for the simple but effective extension. I'm noticing that values may show up multiple times if they are declared multiple times. For example:

```css
:root {
--my-var: blue;
}
.dark-mode {
--my-var: lightblue;
}
```

will cause my-var to show up twice.

![image](https://user-images.githubusercontent.com/20398475/131343845-c3f1094b-beb0-466a-a7bd-b94336bd7c93.png)
